# Generated by Django 3.2.16 on 2023-02-03 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto', '0003_auto_20230203_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_CarAd', to=settings.AUTH_USER_MODEL),
        ),
    ]
