# Generated by Django 3.2.16 on 2023-02-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_rename_phonenumber_carad_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
