# Generated by Django 3.2.16 on 2023-02-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_rename_phonenumber_carad_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carad',
            old_name='number',
            new_name='phonenumber',
        ),
        migrations.AlterField(
            model_name='carad',
            name='year',
            field=models.DateField(),
        ),
    ]
