# Generated by Django 3.2.16 on 2023-02-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_rename_phonenumber_carad_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carad',
            old_name='year',
            new_name='caryear',
        ),
    ]
