# Generated by Django 3.2.16 on 2023-02-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_rename_year_carad_caryear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carad',
            old_name='caryear',
            new_name='year',
        ),
    ]
