# Generated by Django 3.2.16 on 2023-02-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_alter_carad_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='year',
            field=models.DateField(),
        ),
    ]
